# Generated by Django 4.1 on 2022-12-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('latitude', models.TextField()),
                ('longtitude', models.TextField()),
                ('adress', models.TextField()),
                ('image_links', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
